  name: Release Keycloak legacy containers
  on:
    workflow_dispatch:
      inputs:
        tag:
          description: '<tag>-legacy'
          required: true
          default: 'latest'
    push:
      tags:
        - '[0-9]+.[0-9]+.[0-9]+'
  concurrency: keycloak-container-legacy-release

  jobs:
    publish:
      if: github.repository == 'sakazuki/keycloak-containers'
      runs-on: ubuntu-latest
      strategy:
        matrix:
          include:
            - image: keycloak
              context: server
            - image: keycloak-init-container
              context: keycloak-init-container

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: sakazuki/${{ matrix.image }}
          tags: |
            type=raw,value={{tag}}-legacy
            type=raw,value=legacy

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
